component: apigateway
app: appDemo
stage: dev
name: apigwDemo

inputs:
  region: ap-guangzhou
  protocols:
    - http
    - https
  serviceName: 'sls_apigw_test'
  environment: release
  endpoints:
    - path: /
      protocol: HTTP
      method: ANY
      apiName: index
      function:
        functionName: serverless-unit-test
